# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Navigate to project directory
      working-directory: StorageDemo # Replace with the relative path to your project directory
      run: pwd

    - name: Restore dependencies
      working-directory: StorageDemo # Replace with the relative path to your project directory
      run: dotnet restore

    - name: Build
      working-directory: StorageDemo # Replace with the relative path to your project directory
      run: dotnet build --no-restore --configuration Release

    - name: Test
      working-directory: StorageDemo # Replace with the relative path to your project directory
      run: dotnet test --no-build --verbosity normal